# Drasl default config file

# Example: drasl.example.com
Domain = "CHANGEME"

# Example: https://drasl.example.com
BaseURL = "https://CHANGEME"

# List of usernames who automatically become admins of the Drasl instance
DefaultAdmins = [""]

# UUIDs of new players match their player UUIDs in online-mode=false servers
PlayerUUIDGeneration = "offline"

# Registration with username and password is allowed but requires an invite
[RegistrationUsernamePassword.CreateNewPlayer]
Allow = true
RequireInvite = true
